name: "Build iEDA Offline Environment"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    name: Check on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Flake check
        run: nix flake check # we only check on x86_64-linux, the iEDA build is not supported on darwin.

  build-bundle:
    name: Build Binary Bundle on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Build iEDA
        run: nix build -L '.#ieda'
      - name: Build iEDA Bundle
        run: nix bundle -L --bundler github:NixOS/bundlers#toRPM '.#ieda'
      - name: Upload iEDA Offline Bundle
        uses: actions/upload-artifact@v4.6.2
        with:
          name: iEDA-Offline-Bundle-RPM
          path: rpm-single-ieda/*.rpm

  build-docker:
    name: Build Docker on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Build iEDA Release Docker
        run: nix build -L '.#releaseDocker'
      - name: Upload iEDA Release Docker
        uses: actions/upload-artifact@v4.6.2
        with:
          name: iEDA-Release-Docker
          path: result